global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/5768c021-481d-4b81-8503-f56fe4d5c108'
          send_resolved: false
